name: marble
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3.1
  - pyg=2.1.0
  - pytorch-cluster=1.6.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.15
  - numpy=1.23.3
  - pandas=1.4.4
  - scikit-learn=1.1.2
  - matplotlib
  - ipykernel
  - cython=0.29.32
  - networkx=2.8.4
  - tensorboardx=2.2
  - tqdm=4.64.1
  - pyyaml=6.0
  - pot=0.8.2
  - pip=25.0.1
  - pip:
    - blinker==1.9.0
    - cebra==0.4.0
    - elephant==1.1.1
    - flask==3.1.0
    - flask-basicauth==0.2.0
    - flask-limiter==3.10.1
    - h5py==3.13.0
    - mat73==0.65
    - mne==1.8.0
    - neo==0.14.0
    - numba==0.60.0
    - scipy==1.13.1
    - seaborn==0.13.2
    - umap-learn==0.5.7
    - teaspoon==1.3.1
    - marble==1.0 