# Dataset Construction Configuration

# Data source and processing parameters
# data_dir: '/home/honglab/leijiaxin/MARBLE/preprocessed/bipolar'
data_dir: '/home/honglab/leijiaxin/VEEG/Data/yuquan/Preprocessed_SEEG/wangyaobei'
chunk_size_sec: 200                # Process data in chunks of this duration (seconds)
# max_files: 5                      # Only process the first 3 files for testing

save_dir: '/home/honglab/leijiaxin/MARBLE/Datasets'
# Subject-specific processing
use_subject_format: true            # Use subject-based file format
subject_id: 'wangyaobei'              # Subject ID - will be used if files don't have subject info
# max_subjects: 5                    # Limit number of subjects to process

# Dataset types to create
create_raw_dataset: true
create_bandpower_dataset: true
create_event_segment_dataset: true

# Optional: specify a reference time (will be set to 7AM of first day if not specified)
reference_time: '2024-08-14 07:00:00'

# Raw dataset specific parameters
raw_dataset:
  resample_freq: 50  # Set to null or remove for no resampling
  night_start_hour: 20  # 8PM
  night_end_hour: 6     # 6AM

# Event detection parameters for standard events
event_detection:
  low_band: [80, 250]    # Frequency band for standard events (Hz)
  high_band: [250, 451]  # Frequency band for high-frequency events (Hz)
  rel_thresh: 3.0        # Relative threshold factor
  abs_thresh: 3.0        # Absolute threshold factor
  min_gap: 20            # Minimum gap between events (samples)
  min_last: 30           # Minimum duration of events in ms

# Event segment parameters
event_segments:
  fixed_segment_length_ms: 100 # All segments will have exactly this length
  night_start_hour: 20        # 8PM - Start of night time
  night_end_hour: 6           # 6AM - End of night time

# Bandpower extraction parameters
bandpower:
  window_size_ms: 100    # Window size in milliseconds
  overlap: 0.5           # Overlap between consecutive windows (0.0-1.0)
  bands:                 # Frequency bands to extract (Hz)
    gamma: [80, 250]
    high_gamma: [250, 451]
